name: phigros_library
description: A Flutter client and updater for a local Phigros resource library.
publish_to: "none"
version: 0.1.3+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  archive: ^3.6.1
  crypto: ^3.0.7
  path: ^1.9.0
  path_provider: ^2.1.6
  share_plus: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/catalog/songs.json
    - tools/typetree.json
